import os
import sqlite3
from abc import ABC, abstractmethod

class BaseProvider(ABC):
    @abstractmethod
    def generate(self, prompt: str, json_mode: bool = False) -> str:
        """
        Generates text using the active LLM provider.
        
        Args:
            prompt (str): The prompt for the LLM.
            json_mode (bool): Whether to enforce JSON output mode.
            
        Returns:
            str: The text content generated by the model.
        """
        pass

    def log_call(self, provider: str, model: str, prompt: str, response: str, duration_ms: int, success: bool):
        """
        Logs metadata about the LLM call into the database.
        """
        try:
            current_dir = os.path.dirname(os.path.abspath(__file__))
            db_path = os.path.join(os.path.dirname(current_dir), "db", "outreach.db")
            
            # Make sure we don't fail if DB isn't initialized yet
            if not os.path.exists(db_path):
                return

            conn = sqlite3.connect(db_path)
            cursor = conn.cursor()
            
            prompt_len = len(prompt)
            response_len = len(response) if response else 0
            status = "success" if success else "failure"
            
            cursor.execute(
                """INSERT INTO llm_logs (provider, model, prompt_length, response_length, execution_time_ms, status)
                   VALUES (?, ?, ?, ?, ?, ?)""",
                (provider, model, prompt_len, response_len, duration_ms, status)
            )
            conn.commit()
            conn.close()
        except Exception as e:
            # Print a warning but do not interrupt the core flow
            print(f"[Warning] Failed to write LLM log to database: {e}")
